name: Limeditor – 编程，我们是认真的！
markdown: redcarpet
highlighter: pygments
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock']

paginate: 5
paginate_path: blog/page:num

nav:
  - text: 主页
    url: /
  - text: 博客
    url: /blog/
  - text: 插件
    url: /addons/
  - text: 论坛
    url: http://www.baidu.com/
  - text: 关于
    url: /about.html
