name: limeditor – An Open Source Web IDE
markdown: redcarpet
highlighter: pygments
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock']

paginate: 5
paginate_path: blog/page:num

nav:
  - text: News
    url: /news/
  - text: Blog
    url: /blog/
  - text: Addons
    url: /addons/
  - text: Forum
    url: http://www.baidu.com/
  - text: About
    url: /about.html
