name: Lime – An Open Source Text Editor
markdown: redcarpet
highlighter: pygments
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock']

paginate: 5
paginate_path: blog/page:num

nav:
  - text: Blog
    url: /blog/
  - text: Contributing
    url: /contribute.html
  - text: Wiki
    url: https://github.com/limetext/lime/wiki
